ACCOUNT_TYPES = (
    ('bank', 'Bank account'),
    ('wallet', 'Wallet account'),
)

CURRENCIES = (
    ('EUR','Euro'),
    ('GBP','GB Pound'),
    ('USD','US Dollar'),
    ('AFN','Afghani'),
    ('DZD','Algerian Dinar'),
    ('ARS','Argentine Peso'),
    ('AMD','Armenian Dram'),
    ('AWG','Aruban Florin'),
    ('AUD','Australian Dollar'),
    ('AZN','Azerbaijanian Manat'),
    ('BSD','Bahamian Dollar'),
    ('BHD','Bahraini Dinar'),
    ('THB','Baht'),
    ('PAB','Balboa'),
    ('BBD','Barbados Dollar'),
    ('BYR','Belarussian Ruble'),
    ('BZD','Belize Dollar'),
    ('BMD','Bermudian Dollar'),
    ('VEF','Bolivar Fuerte'),
    ('BOB','Boliviano'),
    ('BRL','Brazilian Real'),
    ('BND','Brunei Dollar'),
    ('BGN','Bulgarian Lev'),
    ('BIF','Burundi Franc'),
    ('CAD','Canadian Dollar'),
    ('CVE','Cape Verde Escudo'),
    ('KYD','Cayman Islands Dollar'),
    ('GHS','Cedi'),
    ('XOF','CFA Franc BCEAO'),
    ('XAF','CFA Franc BEAC'),
    ('XPF','CFP Franc'),
    ('CLP','Chilean Peso'),
    ('COP','Colombian Peso'),
    ('KMF','Comoro Franc'),
    ('BAM','Convertible Marks'),
    ('NIO','Cordoba Oro'),
    ('CRC','Costa Rican Colon'),
    ('HRK','Croatian Kuna'),
    ('CUC','Cuba Convertible Peso'),
    ('CUP','Cuban Peso'),
    ('CZK','Czech Koruna'),
    ('GMD','Dalasi'),
    ('DKK','Danish Krone'),
    ('MKD','Denar'),
    ('DJF','Djibouti Franc'),
    ('STD','Dobra'),
    ('DOP','Dominican Peso'),
    ('VND','Dong'),
    ('XCD','East Caribbean Dollar'),
    ('EGP','Egyptian Pound'),
    ('ETB','Ethiopian Birr'),
    ('FKP','Falkland Islands Pound'),
    ('FJD','Fiji Dollar'),
    ('HUF','Forint'),
    ('CDF','Franc Congolais'),
    ('GIP','Gibraltar Pound'),
    ('HTG','Gourde'),
    ('PYG','Guarani'),
    ('GNF','Guinea Franc'),
    ('GYD','Guyana Dollar'),
    ('HKD','Hong Kong Dollar'),
    ('UAH','Hryvnia'),
    ('ISK','Iceland Krona'),
    ('INR','Indian Rupee'),
    ('IRR','Iranian Rial'),
    ('IQD','Iraqi Dinar'),
    ('JMD','Jamaican Dollar'),
    ('JOD','Jordanian Dinar'),
    ('KES','Kenyan Shilling'),
    ('PGK','Kina'),
    ('LAK','Kip'),
    ('KWD','Kuwaiti Dinar'),
    ('MWK','Kwacha'),
    ('AOA','Kwanza'),
    ('MMK','Kyat'),
    ('GEL','Lari'),
    ('LBP','Lebanese Pound'),
    ('ALL','Lek'),
    ('HNL','Lempira'),
    ('SLL','Leone'),
    ('LRD','Liberian Dollar'),
    ('LYD','Libyan Dinar'),
    ('SZL','Lilangeni'),
    ('LSL','Loti'),
    ('MGA','Malagascy Ariary'),
    ('MYR','Malaysian Ringgit'),
    ('MUR','Mauritius Rupee'),
    ('MXN','Mexican Peso'),
    ('MXV','Mexican Unidad de Inversion'),
    ('MDL','Moldovan Leu'),
    ('MAD','Moroccan Dirham'),
    ('MZN','Mozambique Metical'),
    ('BOV','Mvdol'),
    ('NGN','Naira'),
    ('ERN','Nakfa'),
    ('NAD','Namibian Dollar'),
    ('NPR','Nepalese Rupee'),
    ('ANG','Netherlands Antillian Guilder'),
    ('ILS','New Israeli Sheqel'),
    ('RON','Romanian Leu'),
    ('TWD','New Taiwan Dollar'),
    ('TRY','Turkish Lira'),
    ('NZD','New Zealand Dollar'),
    ('BTN','Ngultrum'),
    ('KPW','North Korean Won'),
    ('NOK','Norwegian Krone'),
    ('PEN','Nuevo Sol'),
    ('MRO','Ouguiya'),
    ('TOP','Paanga'),
    ('PKR','Pakistan Rupee'),
    ('MOP','Pataca'),
    ('UYU','Peso Uruguayo'),
    ('PHP','Philippine Peso'),
    ('BWP','Pula'),
    ('QAR','Qatari Rial'),
    ('GTQ','Quetzal'),
    ('ZAR','Rand'),
    ('OMR','Rial Omani'),
    ('KHR','Riel'),
    ('MVR','Rufiyaa'),
    ('IDR','Rupiah'),
    ('RUB','Russian Ruble'),
    ('RWF','Rwanda Franc'),
    ('XDR','SDR'),
    ('SHP','Saint Helena Pound'),
    ('SAR','Saudi Riyal'),
    ('RSD','Serbian Dinar'),
    ('SCR','Seychelles Rupee'),
    ('SGD','Singapore Dollar'),
    ('SBD','Solomon Islands Dollar'),
    ('KGS','Som'),
    ('SOS','Somali Shilling'),
    ('TJS','Somoni'),
    ('LKR','Sri Lanka Rupee'),
    ('SDG','Sudanese Pound'),
    ('SRD','Surinam Dollar'),
    ('SEK','Swedish Krona'),
    ('CHF','Swiss Franc'),
    ('SYP','Syrian Pound'),
    ('BDT','Taka'),
    ('WST','Tala'),
    ('TZS','Tanzanian Shilling'),
    ('KZT','Tenge'),
    ('TTD','Trinidad and Tobago Dollar'),
    ('MNT','Tugrik'),
    ('TND','Tunisian Dinar'),
    ('TMT','Turkmenistan New Manat'),
    ('AED','UAE Dirham'),
    ('UGX','Uganda Shilling'),
    ('COU','Unidad de Valor Real'),
    ('CLF','Unidades de formento'),
    ('UYI','Uruguay Peso en Unidades Indexadas'),
    ('UZS','Uzbekistan Sum'),
    ('VUV','Vatu'),
    ('CHE','WIR Euro'),
    ('CHW','WIR Franc'),
    ('KRW','Won'),
    ('YER','Yemeni Rial'),
    ('JPY','Yen'),
    ('CNY','Yuan Renminbi'),
    ('ZMW','Zambian Kwacha'),
    ('ZWL','Zimbabwe Dollar'),
    ('PLN','Zloty'),
    ('BTC','Bitcoin'),
)

STATUS_TYPES = (
    ('DRAFT', 'DRAFT'),
    ('APPROVED', 'APPROVED'),
    ('PAUSED', 'PAUSED'),
    ('CANCELLED', 'CANCELLED'),
    ('COMPLETED', 'COMPLETED'),
)
