# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name=b'Institution id')),
                ('short_name', models.CharField(max_length=32, verbose_name=b'Short name')),
                ('full_name', models.CharField(max_length=255, verbose_name=b'Full name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'Logo')),
                ('website', models.URLField(max_length=255, verbose_name=b'Website')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
    ]
