# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synenosis', '0002_bankaccount_walletaccount'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""CREATE OR REPLACE VIEW synenosis_account AS
(SELECT 'bank' as account_type, account_id, id, number, label, balance, currency, institution_id FROM synenosis_bankaccount)
UNION
(SELECT 'wallet' as account_type, account_id, id, number, label, balance, currency, institution_id FROM synenosis_walletaccount);""",
            reverse_sql="DROP VIEW IF EXISTS synenosis_account",
            state_operations=None,
        ),
    ]
