# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synenosis', '0006_auto_20160424_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='iban',
            new_name='IBAN',
        ),
    ]
