# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synenosis', '0009_auto_20160424_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(max_length=128, verbose_name=b'Type'),
        ),
    ]
