# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import synenosis.models


class Migration(migrations.Migration):

    dependencies = [
        ('synenosis', '0011_auto_20160424_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(default=synenosis.models.get_uuid, max_length=255, verbose_name=b'Account id'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_id',
            field=models.CharField(default=synenosis.models.get_uuid, max_length=255, verbose_name=b'Institution id'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_uuid',
            field=models.CharField(default=synenosis.models.get_uuid, max_length=255, verbose_name=b'Transaction uuid'),
        ),
        migrations.AlterField(
            model_name='walletaccount',
            name='account_id',
            field=models.CharField(default=synenosis.models.get_uuid, max_length=255, verbose_name=b'Account id'),
        ),
    ]
