# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synenosis', '0012_auto_20160424_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='other_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Other account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='this_account',
            field=models.CharField(max_length=255, verbose_name=b'This account'),
        ),
    ]
